name: Maven Build Check

on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - github-actions

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests
